print("Aditya")
print('Aditya')
print("Aditya's Singh")
print('Aditya\'s "Singh"')
print("Aditya\nSingh")
print("Aditya" + "Singh")
print("Aditya" + " " + "Singh")
print("Aditya" * 3)
print('c:\docs\navin')
print(r'c:\docs\navin')
